/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestione_magazzione;

import java.util.Random;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author free
 */
public class JF_Interfaccia extends javax.swing.JFrame {

    /**
     * Creates new form JF_Interfaccia
     */
    public JF_Interfaccia() {
        initComponents();
        JP_Gestione.setVisible(false);
        JP_Lista.setVisible(false);
        JP_Nuovo.setVisible(false);
        JTF_Codice.setEditable(false);
        ((JSpinner.DefaultEditor) JSP_Quantita.getEditor()).getTextField().setEditable(false);
       JSP_Quantita.setModel(new SpinnerNumberModel(0, 0, 1000, 1));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JB_LIsta = new javax.swing.JButton();
        JB_Nuovo = new javax.swing.JButton();
        JB_Gestione = new javax.swing.JButton();
        JP_Nuovo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JTF_Nome = new javax.swing.JTextField();
        CB_Categorie = new javax.swing.JComboBox<>();
        JTF_Codice = new javax.swing.JTextField();
        JTF_Prezzo = new javax.swing.JTextField();
        JSP_Quantita = new javax.swing.JSpinner();
        JB_Aggiungi = new javax.swing.JButton();
        JB_GeneraCodice = new javax.swing.JButton();
        JP_Lista = new javax.swing.JPanel();
        JP_Gestione = new javax.swing.JPanel();
        JCB_Prodotti = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JTF_NomeMod = new javax.swing.JTextField();
        CB_CategorieMod = new javax.swing.JComboBox<>();
        JTF_CodiceMod = new javax.swing.JTextField();
        JTF_PrezzoMod = new javax.swing.JTextField();
        JSP_QuantitaMod = new javax.swing.JSpinner();
        JB_Aggiungi1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MAGAZZINI RIZZI.png"))); // NOI18N

        JB_LIsta.setBackground(new java.awt.Color(255, 102, 102));
        JB_LIsta.setForeground(new java.awt.Color(0, 0, 0));
        JB_LIsta.setText("LISTA");
        JB_LIsta.setBorder(null);
        JB_LIsta.setFocusable(false);
        JB_LIsta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_LIstaMouseClicked(evt);
            }
        });

        JB_Nuovo.setBackground(new java.awt.Color(255, 102, 102));
        JB_Nuovo.setForeground(new java.awt.Color(0, 0, 0));
        JB_Nuovo.setText("NUOVO PRODOTTO");
        JB_Nuovo.setBorder(null);
        JB_Nuovo.setFocusable(false);
        JB_Nuovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_NuovoMouseClicked(evt);
            }
        });

        JB_Gestione.setBackground(new java.awt.Color(255, 102, 102));
        JB_Gestione.setForeground(new java.awt.Color(0, 0, 0));
        JB_Gestione.setText("GESTIONE");
        JB_Gestione.setBorder(null);
        JB_Gestione.setFocusable(false);
        JB_Gestione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_GestioneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_LIsta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_Gestione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_Nuovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(JB_Nuovo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_Gestione, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB_LIsta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        jLabel4.setText("INSERISCI UN NUOVO PRODOTTO");

        jLabel5.setText("NOME");

        jLabel6.setText("CATEGORIA");

        jLabel7.setText("CODICE");

        jLabel8.setText("PREZZO");

        jLabel9.setText("QUANTITA'");

        JTF_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTF_NomeKeyReleased(evt);
            }
        });

        CB_Categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia", "Cibo", "Accessori", "Bricolage", " " }));

        JTF_Prezzo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTF_PrezzoKeyReleased(evt);
            }
        });

        JB_Aggiungi.setBackground(new java.awt.Color(255, 51, 0));
        JB_Aggiungi.setText("ADD");
        JB_Aggiungi.setBorder(null);
        JB_Aggiungi.setFocusable(false);
        JB_Aggiungi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AggiungiMouseClicked(evt);
            }
        });

        JB_GeneraCodice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_GeneraCodiceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JP_NuovoLayout = new javax.swing.GroupLayout(JP_Nuovo);
        JP_Nuovo.setLayout(JP_NuovoLayout);
        JP_NuovoLayout.setHorizontalGroup(
            JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_NuovoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_NuovoLayout.createSequentialGroup()
                        .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JTF_Nome)
                                .addComponent(CB_Categorie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(JP_NuovoLayout.createSequentialGroup()
                                .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JSP_Quantita, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTF_Prezzo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(JTF_Codice, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JB_GeneraCodice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(131, 131, 131))
                    .addGroup(JP_NuovoLayout.createSequentialGroup()
                        .addComponent(JB_Aggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JP_NuovoLayout.setVerticalGroup(
            JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_NuovoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CB_Categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_GeneraCodice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(JTF_Codice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JTF_Prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_NuovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSP_Quantita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(JB_Aggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JP_ListaLayout = new javax.swing.GroupLayout(JP_Lista);
        JP_Lista.setLayout(JP_ListaLayout);
        JP_ListaLayout.setHorizontalGroup(
            JP_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );
        JP_ListaLayout.setVerticalGroup(
            JP_ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        JCB_Prodotti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JCB_ProdottiItemStateChanged(evt);
            }
        });

        jLabel3.setText("Seleziona prodotto");

        jLabel10.setText("-----------------------------------------------------------------------------------------------");

        jLabel11.setText("CODICE");

        jLabel12.setText("PREZZO");

        jLabel13.setText("QUANTITA'");

        JTF_NomeMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTF_NomeModKeyReleased(evt);
            }
        });

        CB_CategorieMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia", "Cibo", "Accessori", "Bricolage", " " }));

        JTF_PrezzoMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTF_PrezzoModKeyReleased(evt);
            }
        });

        JB_Aggiungi1.setBackground(new java.awt.Color(255, 51, 0));
        JB_Aggiungi1.setText("APPLICA");
        JB_Aggiungi1.setBorder(null);
        JB_Aggiungi1.setFocusable(false);
        JB_Aggiungi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_Aggiungi1MouseClicked(evt);
            }
        });

        jLabel14.setText("NOME");

        jLabel15.setText("CATEGORIA");

        javax.swing.GroupLayout JP_GestioneLayout = new javax.swing.GroupLayout(JP_Gestione);
        JP_Gestione.setLayout(JP_GestioneLayout);
        JP_GestioneLayout.setHorizontalGroup(
            JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_GestioneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCB_Prodotti, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JP_GestioneLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JP_GestioneLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JP_GestioneLayout.createSequentialGroup()
                            .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JTF_NomeMod)
                                    .addComponent(CB_CategorieMod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JSP_QuantitaMod, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTF_PrezzoMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(JTF_CodiceMod, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGap(21, 21, 21))
                        .addGroup(JP_GestioneLayout.createSequentialGroup()
                            .addComponent(JB_Aggiungi1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(73, 73, 73)))
        );
        JP_GestioneLayout.setVerticalGroup(
            JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_GestioneLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addComponent(JCB_Prodotti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(323, Short.MAX_VALUE))
            .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JP_GestioneLayout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(JTF_NomeMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(CB_CategorieMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(JTF_CodiceMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(JTF_PrezzoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(JP_GestioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JSP_QuantitaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(JB_Aggiungi1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(81, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JP_Nuovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(198, Short.MAX_VALUE)
                    .addComponent(JP_Lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 200, Short.MAX_VALUE)
                    .addComponent(JP_Gestione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JP_Nuovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(JP_Lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JP_Gestione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_NuovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_NuovoMouseClicked
        JP_Gestione.setVisible(false);
        JP_Lista.setVisible(false);
        JP_Nuovo.setVisible(true);
    }//GEN-LAST:event_JB_NuovoMouseClicked

    private void JB_GestioneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_GestioneMouseClicked
        JP_Gestione.setVisible(true);
        JP_Lista.setVisible(false);
        JP_Nuovo.setVisible(false);
        JCB_Prodotti.removeAllItems();
        for (int i=0;i<Gestione_Magazzione.prodotti.size();i++){
            JCB_Prodotti.addItem(Gestione_Magazzione.prodotti.get(i).getNome());
        }
    }//GEN-LAST:event_JB_GestioneMouseClicked

    private void JB_LIstaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_LIstaMouseClicked
       JP_Gestione.setVisible(false);
        JP_Lista.setVisible(true);
        JP_Nuovo.setVisible(false);
    }//GEN-LAST:event_JB_LIstaMouseClicked

    private void JB_GeneraCodiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_GeneraCodiceMouseClicked
        boolean flag = false;
        int codiceRand;
        do{
          Random rand = new Random();
        codiceRand = rand.nextInt((99999 - 11111) + 1) + 11111;
        
        for (int i=0;i<Gestione_Magazzione.prodotti.size();i++){
            flag = true;
            if (Gestione_Magazzione.prodotti.get(i).getCodice() == codiceRand){
                flag = false;
                i = Gestione_Magazzione.prodotti.size();
            }
            
        }  
        }while(flag == false);
        
        JTF_Codice.setText(String.valueOf(codiceRand));
               
        
    }//GEN-LAST:event_JB_GeneraCodiceMouseClicked

    private void JB_AggiungiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AggiungiMouseClicked
       if(!JTF_Codice.getText().equals("") && !JTF_Nome.getText().equals("") && !JTF_Prezzo.getText().equals("")){
           Prodotto prodotto = new Prodotto(JTF_Nome.getText(), (String)CB_Categorie.getSelectedItem(), Integer.parseInt(JTF_Codice.getText()), (int)JSP_Quantita.getValue(), Float.parseFloat(JTF_Prezzo.getText()));
        Gestione_Magazzione.prodotti.add(prodotto);
        JTF_Codice.setText("");
        JTF_Nome.setText("");
        JTF_Prezzo.setText("");
        JSP_Quantita.setValue(0);
        
       }else{
           System.out.println("Inserisci tutti i dati richiesti dal mio fantastico programma");
       }
       
       
       
        
    }//GEN-LAST:event_JB_AggiungiMouseClicked

    private void JTF_NomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_NomeKeyReleased
        
    }//GEN-LAST:event_JTF_NomeKeyReleased

    private void JTF_PrezzoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_PrezzoKeyReleased
        if (JTF_Prezzo.getText().length()>0){
            if (Character.isDigit(JTF_Prezzo.getText().charAt(JTF_Prezzo.getText().length()-1)) == false && JTF_Prezzo.getText().charAt(JTF_Prezzo.getText().length()-1) != '.'){
                JTF_Prezzo.setText(JTF_Prezzo.getText().substring(0 , JTF_Prezzo.getText().length()-1));
            }
        }
    }//GEN-LAST:event_JTF_PrezzoKeyReleased

    private void JTF_NomeModKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_NomeModKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_NomeModKeyReleased

    private void JTF_PrezzoModKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_PrezzoModKeyReleased
        if (JTF_PrezzoMod.getText().length()>0){
            if (Character.isDigit(JTF_PrezzoMod.getText().charAt(JTF_PrezzoMod.getText().length()-1)) == false && JTF_PrezzoMod.getText().charAt(JTF_PrezzoMod.getText().length()-1) != '.'){
                JTF_PrezzoMod.setText(JTF_PrezzoMod.getText().substring(0 , JTF_PrezzoMod.getText().length()-1));
            }
        }
    }//GEN-LAST:event_JTF_PrezzoModKeyReleased

    private void JB_Aggiungi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_Aggiungi1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_Aggiungi1MouseClicked

    private void JCB_ProdottiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JCB_ProdottiItemStateChanged
        Prodotto prodotto = Gestione_Magazzione.prodotti.get(JCB_Prodotti.getSelectedIndex());
        
        JTF_CodiceMod.setText(String.valueOf(prodotto.getCodice()));
        JTF_NomeMod.setText(prodotto.getNome());
        JTF_PrezzoMod.setText(String.valueOf(prodotto.getPrezzo()));
        CB_CategorieMod.removeAllItems();
        CB_CategorieMod.addItem(prodotto.getCategoria());
    }//GEN-LAST:event_JCB_ProdottiItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Interfaccia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Interfaccia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CB_Categorie;
    public javax.swing.JComboBox<String> CB_CategorieMod;
    public javax.swing.JButton JB_Aggiungi;
    public javax.swing.JButton JB_Aggiungi1;
    public javax.swing.JButton JB_GeneraCodice;
    public javax.swing.JButton JB_Gestione;
    public javax.swing.JButton JB_LIsta;
    public javax.swing.JButton JB_Nuovo;
    public javax.swing.JComboBox<String> JCB_Prodotti;
    public javax.swing.JPanel JP_Gestione;
    public javax.swing.JPanel JP_Lista;
    public javax.swing.JPanel JP_Nuovo;
    public javax.swing.JSpinner JSP_Quantita;
    public javax.swing.JSpinner JSP_QuantitaMod;
    public javax.swing.JTextField JTF_Codice;
    public javax.swing.JTextField JTF_CodiceMod;
    public javax.swing.JTextField JTF_Nome;
    public javax.swing.JTextField JTF_NomeMod;
    public javax.swing.JTextField JTF_Prezzo;
    public javax.swing.JTextField JTF_PrezzoMod;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
